# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@v1.3
      - uses: subosito/flutter-action@v2
        with:
            flutter-version: '3.0.3'
            channel: 'stable'
      - uses: actions/setup-java@v1
        with:
           java-version: '12.x'

      - name: Cleaning project
        run: flutter clean
        
      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test
        
      - name: Build Web
        run: flutter build web --web-renderer html --release 
        
      - name: Deploy
        env:
         SUPER_SECRET: ${{secrets.GITHUB_TOKEN}}
        run: |
          cd build/web
          git init
          git config --global user.email sinigagliafernando@gmail.com
          git config --global user.name fernandosini
          git remote add origin https://fernandosini:$SUPER_SECRET@github.com/fernandosini/biquitous-parakeet.git
          git status
          git checkout -b web-release
          git add .
          git commit -m "update"
          git push origin web-release -f
          
      - name: Build android
        run: flutter build appbundle 
      - uses: actions/upload-artifact@v1
        with:
           name: release-appbundle
           path: build/app/outputs/bundle/release/app-release.aab

      - name: Deploy android
        env:
         SUPER_SECRET: ${{secrets.GITHUB_TOKEN}}
        run: |
          cd build/app/outputs/bundle/release/
          git init
          git config --global user.email sinigagliafernando@gmail.com
          git config --global user.name fernandosini
          git remote add origin https://fernandosini:$SUPER_SECRET@github.com/fernandosini/biquitous-parakeet.git
          git status
          git checkout -b app-production
          git add .
          git commit -m "update"
          git push origin app-production -f     
        
